version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
<<<<<<< Updated upstream
    interval: saturday
=======
    day: saturday
>>>>>>> Stashed changes
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.4.6
  - dependency-name: pytest
    versions:
    - 6.2.2
