#!/bin/bash
TESTING=True \
TEST_DATABASE_URL=sqlite:///./test.db \
IMAGES_SERVICE_ENDPOINT=http://images-service:80/image \
poetry run pytest --cov-report=xml --cov=app
poetry run codecov --commit=$1 -t $2
