"""Add key to entries

Revision ID: 814bd201b949
Revises: 90a6a2007adf
Create Date: 2021-01-04 17:01:20.103501

"""
from alembic import op
from fastapi_utils.guid_type import GUID
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "814bd201b949"
down_revision = "90a6a2007adf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("key", GUID(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries", schema=None) as batch_op:
        batch_op.drop_column("key")

    # ### end Alembic commands ###
