"""Initial migration

Revision ID: 90a6a2007adf
Revises: 
Create Date: 2021-01-03 15:33:00.122969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90a6a2007adf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entries_id"), "entries", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entries_id"), table_name="entries")
    op.drop_table("entries")
    # ### end Alembic commands ###
